[build]
cmd = "cargo build && cp -r ./target/debug/cgmu ./bin/cgmu"

[[custom]]
name = "clean"
cmd = "cargo clean"
run = false

[[custom]]
name = "setup"
cmd = "mkdir -p bin && rustup install stable && rustup default stable"
run = false

[[custom]]
name = "release"
cmd = "cargo build --release && cp -r ./target/release/cgmu ./bin/cgmu"
run = false

[[pre]]
name = "fmt"
cmd = "cargo fmt"
